# Generated by Django 2.2.3 on 2019-07-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='e',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='n',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
