# Generated by Django 2.2.3 on 2019-07-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190731_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rooms',
        ),
    ]
