# Generated by Django 2.2.4 on 2019-08-02 04:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roommanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roommanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rooms.RoomManager')),
                ('n', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
            ],
            bases=('rooms.roommanager',),
        ),
    ]
