# Generated by Django 2.2.4 on 2019-08-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomManager',
        ),
    ]
