# Generated by Django 2.2.4 on 2019-08-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0008_auto_20190802_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
