# Generated by Django 2.2.4 on 2019-08-02 04:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roommanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
            ],
        ),
    ]
