# Generated by Django 2.2.3 on 2019-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_room',
            field=models.CharField(default='start', max_length=255),
        ),
    ]
