# Generated by Django 2.2.4 on 2019-08-02 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190801_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_room',
            field=models.CharField(default='Library', max_length=255),
        ),
    ]
