# Generated by Django 2.2.4 on 2019-08-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190801_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_room',
            field=models.CharField(default='Library', max_length=255),
        ),
    ]
