# Generated by Django 2.2.4 on 2019-08-02 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190802_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
