# Generated by Django 2.2.4 on 2019-08-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190802_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_room',
            field=models.CharField(default='start', max_length=255),
        ),
    ]
